::FOR /F "tokens=*" %%G IN ('DIR /B /AD /S bin') DO RMDIR /S /Q "%%G"
::FOR /F "tokens=*" %%G IN ('DIR /B /AD /S obj') DO RMDIR /S /Q "%%G"
RMDIR /S /Q "AppManager/bin"
RMDIR /S /Q "AppManager/obj"
RMDIR /S /Q "Core/bin"
RMDIR /S /Q "Core/obj"
RMDIR /S /Q "Config/bin"
RMDIR /S /Q "Config/obj"
RMDIR /S /Q "Tests/bin"
RMDIR /S /Q "Tests/obj"