using System;
using System.Collections.Generic;
using System.Text;

namespace AppManager.Core.Utilities
{
    /// <summary>
    /// Represents the method that will handle events that provide a boolean result or condition.
    /// </summary>
    /// <param name="sender">The source of the event.</param>
    /// <param name="e">An <see cref="EventArgs"/> that contains the event data.</param>
    /// <returns>A boolean value indicating the result or condition of the event handling.</returns>
    public delegate void TrueEventHandler(object sender, EventArgs e);

    /// <summary>
    /// Represents the method that will handle events with custom event arguments that provide a boolean result.
    /// </summary>
    /// <typeparam name="TEventArgs">The type of the event data generated by the event.</typeparam>
    /// <param name="sender">The source of the event.</param>
    /// <param name="e">An object of type <typeparamref name="TEventArgs"/> that contains the event data.</param>
    /// <returns>A boolean value indicating the result or condition of the event handling.</returns>
    public delegate void TrueEventHandler<TEventArgs>(object sender, TEventArgs e) where TEventArgs : EventArgs;

    public class EventHandlers
    {
    }
}
